"""Turning "what should this binary run?" into argv the launcher can execute.

Three ways to say it, in the order a human is likely to reach for them:

    hello.py                  a script path, relative to the app directory
    lotek                     a console script declared in [project.scripts]
    app.cli:main              a module:callable, the same spelling [project.scripts] uses

The third is resolved here, at BUILD time, into plain argv. The launcher stays unchanged
and knows nothing about entry-point syntax — one less place for the two sides to disagree.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

__all__ = ["EntryPointError", "is_object_ref", "argv_for_object_ref", "resolve_entrypoint",
           "verify_object_ref", "verify_script_file", "top_level_callables",
           "suggest_object_refs", "console_script_is_declared"]

# When a project is importable but has nothing to execute, haru-pack refuses — but it can
# still hand the operator the exact flag to type. These are the names a Python program's
# entry function is actually called, most likely first, so the suggestion at the top of the
# list is usually the right one. This orders a SUGGESTION; it never picks (INV-BUILD-03).
PREFERRED_CALLABLES = ("main", "cli", "run", "serve", "start", "app", "create_app")

# `module.path:callable` — the packaging spec's object reference. The attribute half may be
# dotted (`pkg.mod:Cls.method`); neither half may be empty.
_OBJECT_REF = re.compile(r"^(?P<module>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)"
                         r":(?P<attr>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)$")

# A script filename or a console-script name: no whitespace, no shell metacharacters. This
# string ends up as argv for the launcher, so anything exotic is a mistake worth catching at
# build time rather than on a customer's machine.
_PLAIN_NAME = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.\-/]*$")


class EntryPointError(ValueError):
    """An --entry-point string that is not a usable entry point."""


def is_object_ref(spec: str) -> bool:
    return bool(_OBJECT_REF.match(spec or ""))


def argv_for_object_ref(spec: str, prog: str) -> list:
    """argv that imports `module`, calls `attr()`, and exits with its return value.

    Mirrors what a console script generated by an installer does, including
    `raise SystemExit(...)` on the return value, so a CLI that returns an exit code keeps
    working. `sys.argv[0]` is set to `prog` because `python -c` leaves it as `"-c"`, which
    argparse and click would otherwise print as the program name in help and errors.
    """
    m = _OBJECT_REF.match(spec or "")
    if not m:
        raise EntryPointError(
            f"{spec!r} is not a module:callable reference. Expected something like "
            f"'app.cli:main' — a module path, a colon, then the function to call.")
    module, attr = m.group("module"), m.group("attr")
    root, _, rest = attr.partition(".")
    call = f"_o.{rest}" if rest else "_o"
    code = (f"import sys;sys.argv[0]={prog!r};"
            f"from {module} import {root} as _o;"
            f"raise SystemExit({call}())")
    return ["python", "-c", code]


def _module_file(module: str, project: Path):
    """The file a dotted module name would live in, under a flat or `src/` layout.

    Returns None when nothing matches — which is a normal answer, not a failure: the module
    may legitimately come from a dependency rather than from the project tree.
    """
    rel = module.replace(".", "/")
    for root in (project, project / "src"):
        for cand in (root / f"{rel}.py", root / rel / "__init__.py"):
            if cand.is_file():
                return cand
    return None


def _defines(tree: ast.Module, wanted: str) -> bool:
    """Does this module bind `wanted` at top level, by any of the usual means?

    Import aliases count: a package whose `__init__.py` does `from .impl import main` really
    does provide `main`, and refusing that would be worse than not checking at all.
    """
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if node.name == wanted:
                return True
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for al in node.names:
                if al.name == "*":
                    return True          # `import *` — cannot know; assume it provides it
                if (al.asname or al.name.split(".")[0]) == wanted:
                    return True
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == wanted:
                    return True
                if isinstance(t, (ast.Tuple, ast.List)):
                    for e in t.elts:
                        if isinstance(e, ast.Name) and e.id == wanted:
                            return True
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and node.target.id == wanted:
                return True
        elif isinstance(node, ast.Try):
            # `try: from fast import main / except ImportError: from slow import main`
            for sub in [*node.body, *node.orelse, *node.finalbody,
                        *[h for hh in node.handlers for h in hh.body]]:
                if isinstance(sub, (ast.Import, ast.ImportFrom)):
                    for al in sub.names:
                        if al.name == "*" or (al.asname or al.name.split(".")[0]) == wanted:
                            return True
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                        and sub.name == wanted:
                    return True
        elif isinstance(node, ast.If):
            # `if TYPE_CHECKING:` and platform guards; be generous, this is a typo check
            for sub in [*node.body, *node.orelse]:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                        and sub.name == wanted:
                    return True
                if isinstance(sub, (ast.Import, ast.ImportFrom)):
                    for al in sub.names:
                        if al.name == "*" or (al.asname or al.name.split(".")[0]) == wanted:
                            return True
    return False


def _parse(path: Path):
    try:
        return ast.parse(path.read_text(encoding="utf-8", errors="replace"),
                         filename=str(path))
    except (SyntaxError, ValueError, OSError):
        return None


def top_level_callables(path) -> list:
    """Top-level `def`/`async def`/`class` names in a module, preferred names first.

    Used to turn a refusal into something copy-pasteable. Ordering by
    `PREFERRED_CALLABLES` means the suggestion an operator sees first is the one a program's
    entry function is usually called.
    """
    tree = _parse(Path(path))
    if tree is None:
        return []
    names = [n.name for n in tree.body
             if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
             and not n.name.startswith("_")]
    rank = {n: i for i, n in enumerate(PREFERRED_CALLABLES)}
    return sorted(names, key=lambda n: (rank.get(n, len(rank)), n))


def suggest_object_refs(module: str, project) -> list:
    """`module:callable` specs an operator could plausibly mean, best first."""
    path = _module_file(module, Path(project))
    if path is None:
        return []
    return [f"{module}:{fn}" for fn in top_level_callables(path)]


def has_main_guard(module: str, project) -> bool:
    path = _module_file(module, Path(project))
    if path is None:
        return False
    tree = _parse(path)
    return tree is not None and any(isinstance(n, ast.If) and _is_main_guard(n)
                                   for n in tree.body)


def console_script_is_declared(name: str, project) -> bool:
    """Is `name` a console script this project declares in its own pyproject.toml?

    A False answer is NOT evidence that the entrypoint is wrong. The launcher runs
    `uv run <name>` inside the project environment, which resolves scripts provided by
    *dependencies* too — `gunicorn`, `flask`, `celery`, `uvicorn` are all ordinary,
    correct answers that appear nowhere in `[project.scripts]`. So this feeds a warning,
    never a refusal, unless something else can prove the script is absent.
    """
    from . import tomlio
    pp = Path(project) / "pyproject.toml"
    if not pp.exists():
        return False
    try:
        proj = tomlio.load(pp).get("project") or {}
    except Exception:
        return False
    return name in (proj.get("scripts") or {})


def console_script_in_env(name: str, env_dir) -> bool:
    """Is there an executable called `name` in this environment's script directory?"""
    env_dir = Path(env_dir)
    for d in (env_dir / "bin", env_dir / "Scripts"):
        if (d / name).is_file() or (d / f"{name}.exe").is_file():
            return True
    return False


def verify_console_script(name: str, project, env_dir=None) -> tuple:
    """Decide what can honestly be said about a bare console-script entrypoint.

    Returns `(level, message)` where level is `""`, `"warn"` or `"error"`.

    The launcher runs `uv run <name>` in the project environment, so the set of valid names
    is "console scripts of the project **plus all of its dependencies**" — `gunicorn`,
    `flask`, `celery`, `uvicorn` are all correct and appear nowhere in `[project.scripts]`.
    Refusing on absence from that table would reject working builds, which is its own
    ergonomic failure (docs/PRINCIPLES.md). So:

      * declared in `[project.scripts]`      -> silent, trust the declaration;
      * present in a built environment       -> silent, we can see it;
      * neither, and we HAVE an environment  -> error; nothing can provide it;
      * neither, and we have no environment  -> warn, naming what we could not check.
    """
    if console_script_is_declared(name, project):
        return "", ""
    if env_dir is not None and console_script_in_env(name, env_dir):
        return "", ""
    from . import tomlio
    declared = []
    pp = Path(project) / "pyproject.toml"
    if pp.exists():
        try:
            declared = sorted((tomlio.load(pp).get("project") or {}).get("scripts") or {})
        except Exception:
            declared = []
    hint = ("\nThis project declares: " + ", ".join(declared)) if declared else ""
    if env_dir is not None:
        return "error", (
            f"entrypoint {name!r} is not a console script this build can run: it is not in "
            f"[project.scripts], and no `{name}` was installed into the build environment "
            f"by the project or any of its dependencies.{hint}\n"
            f"On the target this would fail with a 'command not found' from uv.")
    return "warn", (
        f"entrypoint {name!r} is not declared in [project.scripts] and is not a file in the "
        f"project. haru-pack cannot verify it at this tier — it will work only if one of "
        f"your dependencies provides a `{name}` console script (gunicorn and flask do, for "
        f"example).{hint}\nBuild with --thick to have this checked against a real "
        f"environment, or pass a module:callable instead.")


def verify_script_file(spec: str, project) -> str:
    """A `.py` entrypoint has to exist in the project, or the launcher runs nothing.

    The launcher resolves a `.py` token to `<staged app dir>/<token>` — so a filename that
    is not in the tree is a guaranteed runtime failure, and one we can be certain about at
    build time. `-e nosuch.py` used to build cleanly.
    """
    if not spec.endswith(".py"):
        return ""
    p = Path(project) / spec
    if p.is_file():
        return ""
    near = sorted(q.name for q in Path(project).glob("*.py"))
    hint = ("\nPython files at the project root: " + ", ".join(near[:8])) if near else ""
    return (f"entrypoint {spec!r} is a script filename, but {p} does not exist. The "
            f"launcher resolves a .py entrypoint inside the payload, so this would run "
            f"nothing on the target.{hint}")


def verify_object_ref(spec: str, project) -> str:
    """Confirm `module:callable` actually names something, or return why it does not.

    A `module:callable` entrypoint is turned into a `python -c "from module import attr"`
    argv at build time and *nothing ever checks that the import works*. So `-e app:mian`
    built cleanly, exited 0, and failed on the customer's machine at first run — the exact
    failure this project's design rules single out as the worst kind.

    Checked statically, by parsing the module rather than importing it. That is deliberate:
    an import would execute the project's code on the build host, and would not work at all
    for a cross-compiled target. The cost is that this cannot see attributes created
    dynamically, so the rule is **only refuse when we are sure**:

      * module file not found in the project tree -> say nothing (it may come from a
        dependency, or from a `src/` layout we do not recognise);
      * module found but unparseable -> say nothing (not our job to lint their syntax);
      * module found, parsed, and the name is genuinely absent -> refuse.

    Returns an empty string when there is no problem to report.
    """
    m = _OBJECT_REF.match(spec or "")
    if not m:
        return ""
    module, attr = m.group("module"), m.group("attr")
    root_attr = attr.split(".")[0]
    path = _module_file(module, Path(project))
    if path is None:
        return ""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"),
                         filename=str(path))
    except (SyntaxError, ValueError, OSError):
        return ""
    if _defines(tree, root_attr):
        return ""
    hint = ""
    refs = suggest_object_refs(module, project)
    if refs:
        hint = ("\n\nDid you mean one of these? Copy one:\n"
                + "\n".join(f"    --entry-point {r}" for r in refs[:5]))
    if any(isinstance(n, ast.If) and _is_main_guard(n) for n in tree.body):
        hint += (
            f"\n\n{path.name} has an `if __name__ == \"__main__\":` block. That is NOT the "
            f"same thing as `{module}:{root_attr}` — the guard runs when the file is "
            f"executed (`python -m {module}`), and cannot be imported and called. Either "
            f"move that code into a function and point at it, or use a `__main__.py` and "
            f"let haru-pack run `python -m {module}`.")
    return (f"entrypoint {spec!r} names `{root_attr}` in `{module}`, but {path} defines no "
            f"`{root_attr}`.{hint}")


def _is_main_guard(node: ast.If) -> bool:
    t = node.test
    if not isinstance(t, ast.Compare) or len(t.comparators) != 1:
        return False
    left, right = t.left, t.comparators[0]
    return (isinstance(left, ast.Name) and left.id == "__name__"
            and isinstance(right, ast.Constant) and right.value == "__main__")


def resolve_entrypoint(spec, *, name: str, kind: str) -> list:
    """Normalize any accepted entrypoint spelling into argv.

    A list is passed through untouched — it is already argv, and second-guessing a caller
    who spelled it out explicitly is how you end up with a tool nobody can predict.
    """
    if isinstance(spec, (list, tuple)):
        return list(spec)
    if not isinstance(spec, str) or not spec.strip():
        raise EntryPointError(f"empty entrypoint for {name!r}")
    spec = spec.strip()
    if is_object_ref(spec):
        return argv_for_object_ref(spec, prog=name)
    if ":" in spec:
        # A colon means an object reference was intended. Falling through to "treat it as a
        # command name" would turn `app.cli:` into a search for a console script literally
        # called "app.cli:", and the operator would get "command not found" at RUNTIME, on a
        # customer machine, instead of a typo report at build time.
        raise EntryPointError(
            f"{spec!r} looks like a module:callable reference but is malformed. Expected "
            f"'package.module:function' — both halves required, one colon.")
    if not _PLAIN_NAME.match(spec):
        raise EntryPointError(
            f"{spec!r} is not a usable entrypoint. Give a script filename (app.py), a "
            f"console-script name from [project.scripts] (lotek), or a module:callable "
            f"(app.cli:main).")
    return [spec]        # a script filename or a console-script name; the launcher resolves it
