"""Turning "what should this binary run?" into argv the launcher can execute.

Three ways to say it, in the order a human is likely to reach for them:

    hello.py                  a script path, relative to the app directory
    lotek                     a console script declared in [project.scripts]
    app.cli:main              a module:callable, the same spelling [project.scripts] uses

The third is resolved here, at BUILD time, into plain argv. The launcher stays unchanged
and knows nothing about entry-point syntax — one less place for the two sides to disagree.
"""
from __future__ import annotations

import re

__all__ = ["EntryPointError", "is_object_ref", "argv_for_object_ref", "resolve_entrypoint"]

# `module.path:callable` — the packaging spec's object reference. The attribute half may be
# dotted (`pkg.mod:Cls.method`); neither half may be empty.
_OBJECT_REF = re.compile(r"^(?P<module>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)"
                         r":(?P<attr>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)$")

# A script filename or a console-script name: no whitespace, no shell metacharacters. This
# string ends up as argv for the launcher, so anything exotic is a mistake worth catching at
# build time rather than on a customer's machine.
_PLAIN_NAME = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.\-/]*$")


class EntryPointError(ValueError):
    """An --entry-point string that is not a usable entry point."""


def is_object_ref(spec: str) -> bool:
    return bool(_OBJECT_REF.match(spec or ""))


def argv_for_object_ref(spec: str, prog: str) -> list:
    """argv that imports `module`, calls `attr()`, and exits with its return value.

    Mirrors what a console script generated by an installer does, including
    `raise SystemExit(...)` on the return value, so a CLI that returns an exit code keeps
    working. `sys.argv[0]` is set to `prog` because `python -c` leaves it as `"-c"`, which
    argparse and click would otherwise print as the program name in help and errors.
    """
    m = _OBJECT_REF.match(spec or "")
    if not m:
        raise EntryPointError(
            f"{spec!r} is not a module:callable reference. Expected something like "
            f"'app.cli:main' — a module path, a colon, then the function to call.")
    module, attr = m.group("module"), m.group("attr")
    root, _, rest = attr.partition(".")
    call = f"_o.{rest}" if rest else "_o"
    code = (f"import sys;sys.argv[0]={prog!r};"
            f"from {module} import {root} as _o;"
            f"raise SystemExit({call}())")
    return ["python", "-c", code]


def resolve_entrypoint(spec, *, name: str, kind: str) -> list:
    """Normalize any accepted entrypoint spelling into argv.

    A list is passed through untouched — it is already argv, and second-guessing a caller
    who spelled it out explicitly is how you end up with a tool nobody can predict.
    """
    if isinstance(spec, (list, tuple)):
        return list(spec)
    if not isinstance(spec, str) or not spec.strip():
        raise EntryPointError(f"empty entrypoint for {name!r}")
    spec = spec.strip()
    if is_object_ref(spec):
        return argv_for_object_ref(spec, prog=name)
    if ":" in spec:
        # A colon means an object reference was intended. Falling through to "treat it as a
        # command name" would turn `app.cli:` into a search for a console script literally
        # called "app.cli:", and the operator would get "command not found" at RUNTIME, on a
        # customer machine, instead of a typo report at build time.
        raise EntryPointError(
            f"{spec!r} looks like a module:callable reference but is malformed. Expected "
            f"'package.module:function' — both halves required, one colon.")
    if not _PLAIN_NAME.match(spec):
        raise EntryPointError(
            f"{spec!r} is not a usable entrypoint. Give a script filename (app.py), a "
            f"console-script name from [project.scripts] (lotek), or a module:callable "
            f"(app.cli:main).")
    return [spec]        # a script filename or a console-script name; the launcher resolves it
