"""Turning "what should this binary run?" into argv the launcher can execute.

Three ways to say it, in the order a human is likely to reach for them:

    hello.py                  a script path, relative to the app directory
    lotek                     a console script declared in [project.scripts]
    app.cli:main              a module:callable, the same spelling [project.scripts] uses

The third is resolved here, at BUILD time, into plain argv. The launcher stays unchanged
and knows nothing about entry-point syntax — one less place for the two sides to disagree.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

__all__ = ["EntryPointError", "is_object_ref", "argv_for_object_ref", "resolve_entrypoint",
           "verify_object_ref"]

# `module.path:callable` — the packaging spec's object reference. The attribute half may be
# dotted (`pkg.mod:Cls.method`); neither half may be empty.
_OBJECT_REF = re.compile(r"^(?P<module>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)"
                         r":(?P<attr>[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)$")

# A script filename or a console-script name: no whitespace, no shell metacharacters. This
# string ends up as argv for the launcher, so anything exotic is a mistake worth catching at
# build time rather than on a customer's machine.
_PLAIN_NAME = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.\-/]*$")


class EntryPointError(ValueError):
    """An --entry-point string that is not a usable entry point."""


def is_object_ref(spec: str) -> bool:
    return bool(_OBJECT_REF.match(spec or ""))


def argv_for_object_ref(spec: str, prog: str) -> list:
    """argv that imports `module`, calls `attr()`, and exits with its return value.

    Mirrors what a console script generated by an installer does, including
    `raise SystemExit(...)` on the return value, so a CLI that returns an exit code keeps
    working. `sys.argv[0]` is set to `prog` because `python -c` leaves it as `"-c"`, which
    argparse and click would otherwise print as the program name in help and errors.
    """
    m = _OBJECT_REF.match(spec or "")
    if not m:
        raise EntryPointError(
            f"{spec!r} is not a module:callable reference. Expected something like "
            f"'app.cli:main' — a module path, a colon, then the function to call.")
    module, attr = m.group("module"), m.group("attr")
    root, _, rest = attr.partition(".")
    call = f"_o.{rest}" if rest else "_o"
    code = (f"import sys;sys.argv[0]={prog!r};"
            f"from {module} import {root} as _o;"
            f"raise SystemExit({call}())")
    return ["python", "-c", code]


def _module_file(module: str, project: Path):
    """The file a dotted module name would live in, under a flat or `src/` layout.

    Returns None when nothing matches — which is a normal answer, not a failure: the module
    may legitimately come from a dependency rather than from the project tree.
    """
    rel = module.replace(".", "/")
    for root in (project, project / "src"):
        for cand in (root / f"{rel}.py", root / rel / "__init__.py"):
            if cand.is_file():
                return cand
    return None


def _defines(tree: ast.Module, wanted: str) -> bool:
    """Does this module bind `wanted` at top level, by any of the usual means?

    Import aliases count: a package whose `__init__.py` does `from .impl import main` really
    does provide `main`, and refusing that would be worse than not checking at all.
    """
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if node.name == wanted:
                return True
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for al in node.names:
                if al.name == "*":
                    return True          # `import *` — cannot know; assume it provides it
                if (al.asname or al.name.split(".")[0]) == wanted:
                    return True
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == wanted:
                    return True
                if isinstance(t, (ast.Tuple, ast.List)):
                    for e in t.elts:
                        if isinstance(e, ast.Name) and e.id == wanted:
                            return True
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and node.target.id == wanted:
                return True
        elif isinstance(node, ast.Try):
            # `try: from fast import main / except ImportError: from slow import main`
            for sub in [*node.body, *node.orelse, *node.finalbody,
                        *[h for hh in node.handlers for h in hh.body]]:
                if isinstance(sub, (ast.Import, ast.ImportFrom)):
                    for al in sub.names:
                        if al.name == "*" or (al.asname or al.name.split(".")[0]) == wanted:
                            return True
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                        and sub.name == wanted:
                    return True
        elif isinstance(node, ast.If):
            # `if TYPE_CHECKING:` and platform guards; be generous, this is a typo check
            for sub in [*node.body, *node.orelse]:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                        and sub.name == wanted:
                    return True
                if isinstance(sub, (ast.Import, ast.ImportFrom)):
                    for al in sub.names:
                        if al.name == "*" or (al.asname or al.name.split(".")[0]) == wanted:
                            return True
    return False


def verify_object_ref(spec: str, project) -> str:
    """Confirm `module:callable` actually names something, or return why it does not.

    A `module:callable` entrypoint is turned into a `python -c "from module import attr"`
    argv at build time and *nothing ever checks that the import works*. So `-e app:mian`
    built cleanly, exited 0, and failed on the customer's machine at first run — the exact
    failure this project's design rules single out as the worst kind.

    Checked statically, by parsing the module rather than importing it. That is deliberate:
    an import would execute the project's code on the build host, and would not work at all
    for a cross-compiled target. The cost is that this cannot see attributes created
    dynamically, so the rule is **only refuse when we are sure**:

      * module file not found in the project tree -> say nothing (it may come from a
        dependency, or from a `src/` layout we do not recognise);
      * module found but unparseable -> say nothing (not our job to lint their syntax);
      * module found, parsed, and the name is genuinely absent -> refuse.

    Returns an empty string when there is no problem to report.
    """
    m = _OBJECT_REF.match(spec or "")
    if not m:
        return ""
    module, attr = m.group("module"), m.group("attr")
    root_attr = attr.split(".")[0]
    path = _module_file(module, Path(project))
    if path is None:
        return ""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"),
                         filename=str(path))
    except (SyntaxError, ValueError, OSError):
        return ""
    if _defines(tree, root_attr):
        return ""
    hint = ""
    names = sorted({n.name for n in tree.body
                    if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))})
    if names:
        hint = "\nCallables it does define: " + ", ".join(names[:8])
    if any(isinstance(n, ast.If) and _is_main_guard(n) for n in tree.body):
        hint += (
            f"\n\n{path.name} has an `if __name__ == \"__main__\":` block. That is NOT the "
            f"same thing as `{module}:{root_attr}` — the guard runs when the file is "
            f"executed (`python -m {module}`), and cannot be imported and called. Either "
            f"move that code into a function and point at it, or use a `__main__.py` and "
            f"let haru-pack run `python -m {module}`.")
    return (f"entrypoint {spec!r} names `{root_attr}` in `{module}`, but {path} defines no "
            f"`{root_attr}`.{hint}")


def _is_main_guard(node: ast.If) -> bool:
    t = node.test
    if not isinstance(t, ast.Compare) or len(t.comparators) != 1:
        return False
    left, right = t.left, t.comparators[0]
    return (isinstance(left, ast.Name) and left.id == "__name__"
            and isinstance(right, ast.Constant) and right.value == "__main__")


def resolve_entrypoint(spec, *, name: str, kind: str) -> list:
    """Normalize any accepted entrypoint spelling into argv.

    A list is passed through untouched — it is already argv, and second-guessing a caller
    who spelled it out explicitly is how you end up with a tool nobody can predict.
    """
    if isinstance(spec, (list, tuple)):
        return list(spec)
    if not isinstance(spec, str) or not spec.strip():
        raise EntryPointError(f"empty entrypoint for {name!r}")
    spec = spec.strip()
    if is_object_ref(spec):
        return argv_for_object_ref(spec, prog=name)
    if ":" in spec:
        # A colon means an object reference was intended. Falling through to "treat it as a
        # command name" would turn `app.cli:` into a search for a console script literally
        # called "app.cli:", and the operator would get "command not found" at RUNTIME, on a
        # customer machine, instead of a typo report at build time.
        raise EntryPointError(
            f"{spec!r} looks like a module:callable reference but is malformed. Expected "
            f"'package.module:function' — both halves required, one colon.")
    if not _PLAIN_NAME.match(spec):
        raise EntryPointError(
            f"{spec!r} is not a usable entrypoint. Give a script filename (app.py), a "
            f"console-script name from [project.scripts] (lotek), or a module:callable "
            f"(app.cli:main).")
    return [spec]        # a script filename or a console-script name; the launcher resolves it
