"""Building Nim from source with haru-pack's managed `zig cc`.

The second implementation behind `toolchain.install_nim` (INV-TOOL-03): where choosenim
publishes no binary — notably linux aarch64, a Raspberry Pi you build ON — Nim is built from
its `v<NIM_VERSION>` git tag using the managed zig as the host C compiler, so the board needs
no system gcc, no apt and no sudo. Split out of `toolchain.py` to keep that module under the
statement-line budget (INV-MODULARITY-01); `toolchain` re-exports both names.

Imports of `toolchain`-defined names are function-local on purpose: `toolchain` imports this
module at the bottom of its own body, and a top-level `from .toolchain import ...` here would
close that loop into a circular import.
"""
from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

from .paths import toolchain_dir
from .targets import host_arch, host_os


def _host_zig_cc_shim(zig: str, dest_dir: Path) -> Path:
    """A directory of `cc`/`gcc` shims that run the managed zig as the HOST C compiler, with the
    same GCC-only-flag translation the cross shim uses. Put it FIRST on PATH so any build that
    reaches for `cc`/`gcc` (Nim's csources bootstrap, koch's own codegen) gets zig cc — no system
    compiler required. Returns the directory."""
    from .toolchain import _ZIG_FLAG_MAP
    dest_dir.mkdir(parents=True, exist_ok=True)
    cases = "\n".join(f'    {k}) args="$args {v}" ;;' for k, v in _ZIG_FLAG_MAP.items())
    body = ("#!/bin/sh\n"
            "# generated by haru-pack; see nim_source._host_zig_cc_shim\n"
            'args=""\n'
            'for a in "$@"; do\n'
            "  case \"$a\" in\n"
            f"{cases}\n"
            "    -march=*) ;;\n"
            '    *) args="$args $a" ;;\n'
            "  esac\n"
            "done\n"
            f'exec "{zig}" cc $args\n')
    for name in ("cc", "gcc"):
        p = dest_dir / name
        p.write_text(body, encoding="utf-8")
        p.chmod(0o755)
    return dest_dir


def build_nim_from_source(force: bool = False, log=print) -> str:
    """Build Nim from source using haru-pack's managed `zig cc`, for a host choosenim has no
    binary for (linux aarch64 — a Raspberry Pi you build ON). Returns the nim path.

    This is not a separate command: `install_nim` calls it automatically where `choosenim_asset()`
    is None. Pinned to `NIM_VERSION` via the git tag `v<NIM_VERSION>` (not a haru-pack digest —
    see the module docstring). Needs `git` and network once; ~10-20 min on an arm board."""
    from .toolchain import (NIM_GIT, NIM_VERSION, ToolchainError, find_managed_zig,
                            install_zig)
    dest = toolchain_dir() / "nim-src" / NIM_VERSION
    exe = "nim.exe" if host_os() == "windows" else "nim"
    nim_bin = dest / "bin" / exe
    if nim_bin.exists() and not force:
        return str(nim_bin)
    if host_os() == "windows":
        raise ToolchainError("the zig source-build fallback is for unix hosts (arm Linux); "
                             "on Windows use a choosenim-supported host.")
    if not shutil.which("git"):
        raise ToolchainError("building Nim from source needs `git` on PATH.")
    zig = find_managed_zig() or install_zig(log=log)
    shim = _host_zig_cc_shim(zig, toolchain_dir() / "nim-src" / "zigshim")
    if dest.exists():
        shutil.rmtree(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    log(f"Nim {NIM_VERSION}: choosenim has no binary for {host_os()}-{host_arch()} — building "
        f"from source with zig cc (once, ~10-20 min) …")
    tag = f"v{NIM_VERSION}"
    r = subprocess.run(["git", "clone", "--depth", "1", "--branch", tag, NIM_GIT, str(dest)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise ToolchainError(f"git clone Nim {tag} failed:\n" + (r.stderr or r.stdout)[-800:])
    env = dict(os.environ)
    env["PATH"] = str(shim) + os.pathsep + env.get("PATH", "")
    env["CC"] = str(shim / "cc")
    env["CXX"] = str(shim / "cc")
    log("  csources bootstrap + koch boot + koch tools, via zig cc …")
    r = subprocess.run(["sh", "build_all.sh"], cwd=dest, env=env, capture_output=True, text=True)
    if r.returncode != 0:
        raise ToolchainError("Nim build_all.sh (zig cc) failed:\n" + (r.stderr or r.stdout)[-1500:])
    if not nim_bin.exists():
        raise ToolchainError(f"Nim build reported success but {nim_bin} is missing")
    if host_os() != "windows":
        nim_bin.chmod(nim_bin.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    log(f"Nim ready (built from source with zig): {nim_bin}")
    return str(nim_bin)
