"""INV-CRYPTO-04 / INV-CRYPTO-05 / INV-CRYPTO-06 / INV-SECRET-01 — the hardened container.

These tests are stronger than the rest of the crypto suite in one specific way: most of
them compile `cryptbox.nim` and run it. The container is written by Python and opened by
the real Nim decryptor, in a subprocess, on containers this file mutates byte by byte.
`tests/test_container.py` can only read the Nim as data; here the Nim is the thing under
test, so an offset that agrees on paper but disagrees in practice cannot pass.

What is proven here, precisely:
  * a v2 container written by `crypto.encrypt` is opened by `cryptbox.openContainer`
    (real AES-GCM interop, not a parity assertion about offsets);
  * flipping a header byte that plays NO part in key derivation is rejected — so the
    rejection is attributable to the AEAD tag, which is exactly what INV-CRYPTO-04 claims
    and what the old fixed-magic AAD could not do;
  * a secret typed at the prompt is not echoed, checked over a real pty with ECHO on;
  * a forged (but correctly authenticated) plaintext with a nonsense policy length is
    refused with a diagnostic, not a crash.

What is NOT proven here: constant-time behavior of the tag comparison. That is asserted
against the source, and it is labelled as such — a timing measurement in a pytest
subprocess would be noise, and a green noise-test is worse than an honest source check.
"""
from __future__ import annotations

import os
import pty
import re
import select
import shutil
import struct
import subprocess
import sys
import time
from pathlib import Path

import pytest
from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from haru_pack import crypto

REPO = Path(__file__).resolve().parent.parent
LAUNCHER_DIR = REPO / "src/haru_pack/launcher"
NIM_CRYPTBOX = LAUNCHER_DIR / "cryptbox.nim"
NIM = shutil.which("nim")

SECRET = b"s3cret-license-key"
PAYLOAD = b"PK\x03\x04not-really-a-zip-but-it-round-trips"
ITERS = 2_000                      # keep PBKDF2 out of the way; iters is authenticated, not secret

# A harness that is only the code path the launcher itself takes: isEncrypted -> openContainer.
HARNESS_NIM = """\
## Generated by tests/test_crypto_hardening.py. Exercises cryptbox.nim as the launcher does.
import std/os
import cryptbox

when isMainModule:
  let raw = readFile(paramStr(1))
  if not isEncrypted(raw): quit("harness: not an encrypted container", 9)
  let payload = openContainer(raw)
  writeFile(paramStr(2), payload)
  echo "HARNESS-OK ", payload.len
"""


@pytest.fixture(scope="module")
def harness(tmp_path_factory) -> Path:
    """Compile cryptbox.nim into a runnable decryptor.

    A compile failure is a hard failure, not a skip: a cryptbox.nim that does not build is
    a bricked launcher for every encrypted build.
    """
    if NIM is None:
        pytest.skip("nim not installed; the cross-implementation tests need the real decryptor")
    d = tmp_path_factory.mktemp("cryptbox-harness")
    src = d / "harness.nim"
    src.write_text(HARNESS_NIM, encoding="utf-8")
    exe = d / "harness"
    r = subprocess.run(
        [NIM, "c", "-d:release", f"--path:{LAUNCHER_DIR}", f"--nimcache:{d / 'nimcache'}",
         f"--out:{exe}", str(src)],
        capture_output=True, text=True, cwd=REPO,
    )
    assert r.returncode == 0 and exe.exists(), (
        "cryptbox.nim does not compile — every encrypted build is bricked:\n"
        f"{r.stdout[-4000:]}\n{r.stderr[-4000:]}"
    )
    return exe


def _run(harness_exe: Path, blob: bytes, tmp_path: Path, *,
         secret: bytes | None = SECRET, env_extra: dict[str, str] | None = None):
    """Open `blob` with the real Nim decryptor. Returns (CompletedProcess, payload|None)."""
    box = tmp_path / "box.bin"
    out = tmp_path / "out.bin"
    out.unlink(missing_ok=True)     # a stale file from an earlier run in the same tmp_path
    box.write_bytes(blob)           # would read as "this container opened"
    env = dict(os.environ)
    env.pop("HARUPACK_SECRET", None)
    if secret is not None:
        env["HARUPACK_SECRET"] = secret.decode()
    env.update(env_extra or {})
    proc = subprocess.run([str(harness_exe), str(box), str(out)],
                          capture_output=True, text=True, env=env, timeout=60,
                          stdin=subprocess.DEVNULL)   # never inherit a tty: it would prompt
    return proc, (out.read_bytes() if out.exists() else None)


def _forge(plaintext: bytes, secret: bytes = SECRET) -> bytes:
    """Assemble a v2 container around arbitrary plaintext, correctly authenticated.

    Deliberately does not call `crypto.encrypt`: it lets these tests produce plaintexts
    the encryptor would never emit (a lying policy length), which is the only way to reach
    the post-decryption bounds checks with a container that genuinely passes the tag check.
    """
    salt, nonce = os.urandom(16), os.urandom(12)
    key = crypto.derive_key(secret, salt, ITERS, None, None)
    head_a = (crypto.MAGIC + struct.pack("<HHI", crypto.CONTAINER_VERSION, 0, ITERS)
              + salt + nonce)
    head_b = struct.pack("<H", 0)
    ct_tag = AESGCM(key).encrypt(nonce, plaintext, head_a + head_b)
    return head_a + ct_tag[-16:] + head_b + ct_tag[:-16]


@pytest.fixture
def container() -> bytes:
    """Unbound container: no machine/user binding, so `flags` does NOT feed the KDF.

    That is the whole point. With a bound container a flags edit changes the derived key
    and the open fails for the old, weaker reason. Unbound, the key is identical before
    and after the edit, so a rejection can only have come from the AEAD tag.
    """
    return crypto.encrypt(PAYLOAD, SECRET, iters=ITERS)


def _aad_or_rejected(blob: bytes) -> bytes | None:
    """The AAD for `blob`, or None if the header no longer parses (also a detection)."""
    try:
        return crypto.container_aad(blob)
    except ValueError:
        return None


def _nim_consts() -> dict[str, int]:
    src = NIM_CRYPTBOX.read_text(encoding="utf-8")
    out = {}
    for name, pat in [("ContainerVersion", r"ContainerVersion\s*=\s*(\d+)'u16"),
                      ("TagOff", r"TagOff\s*=\s*(\d+)"),
                      ("HdrFixed", r"HdrFixed\s*=\s*(\d+)")]:
        m = re.search(pat, src)
        assert m, f"cryptbox.nim no longer declares {name}"
        out[name] = int(m.group(1))
    return out


def _nim_proc(name: str) -> str:
    src = NIM_CRYPTBOX.read_text(encoding="utf-8")
    start = src.index(f"proc {name}")
    rest = src[start + 1:]
    nxt = re.search(r"^proc ", rest, re.M)
    return rest[:nxt.start()] if nxt else rest


# --------------------------------------------------------------------------------------
# INV-CRYPTO-02 / INV-CRYPTO-04 — real interop, and the header is really covered
# --------------------------------------------------------------------------------------

@pytest.mark.invariant("INV-CRYPTO-02")
@pytest.mark.invariant("INV-CRYPTO-04")
def test_nim_opens_a_python_written_v2_container(harness, container, tmp_path):
    """The evidence gap this repo was carrying: nothing ever ran both implementations.

    If the Python AAD and the Nim AAD differ by one byte, this fails — and it is the only
    test in the suite that would notice, since offset-parity checks read the Nim as text.
    """
    proc, payload = _run(harness, container, tmp_path)
    assert proc.returncode == 0, f"the real decryptor rejected a fresh container: {proc.stderr}"
    assert payload == PAYLOAD


@pytest.mark.invariant("INV-CRYPTO-04")
def test_flags_edit_is_detected_by_the_tag_not_by_a_key_mismatch(container):
    """The exact red-path INVARIANTS.md writes for INV-CRYPTO-04.

    The container is unbound, so the derived key is provably unchanged by the edit (that
    is asserted, not assumed). The only thing left that can reject it is the tag.
    """
    mutated = bytearray(container)
    mutated[10] ^= crypto.BIND_MACHINE          # the flags field lives at offset 10
    mutated = bytes(mutated)

    salt = container[16:32]
    iters = struct.unpack_from("<I", container, 12)[0]
    key_before = crypto.derive_key(SECRET, salt, iters, None, None)
    key_after = crypto.derive_key(SECRET, mutated[16:32],
                                  struct.unpack_from("<I", mutated, 12)[0], None, None)
    assert key_before == key_after, (
        "precondition: this test only proves tag-attribution if the edit leaves the key alone"
    )
    assert struct.unpack_from("<H", mutated, 10)[0] != struct.unpack_from("<H", container, 10)[0]

    nonce = mutated[32:44]
    tag = mutated[44:60]
    eslen = struct.unpack_from("<H", mutated, 60)[0]
    ct = mutated[62 + eslen:]
    with pytest.raises(InvalidTag):
        AESGCM(key_before).decrypt(nonce, ct + tag, crypto.container_aad(mutated))

    # ...and the pre-INV-CRYPTO-04 reader (AAD = bare magic) would have accepted it happily,
    # which is what made the old behavior "fail-closed" rather than "tamper-evident".
    with pytest.raises(InvalidTag):
        AESGCM(key_before).decrypt(nonce, ct + tag, crypto.MAGIC)


@pytest.mark.invariant("INV-CRYPTO-04")
def test_nim_rejects_a_flags_edit_with_the_correct_secret(harness, container, tmp_path):
    """Same edit, run through the real decryptor with the right secret in the environment.

    Control first: the unmutated container opens. So the rejection below is the edit.
    """
    ok, payload = _run(harness, container, tmp_path)
    assert ok.returncode == 0 and payload == PAYLOAD, "control: the clean container must open"

    mutated = bytearray(container)
    mutated[10] ^= crypto.BIND_MACHINE
    proc, payload = _run(harness, bytes(mutated), tmp_path)
    assert proc.returncode != 0, (
        "the Nim decryptor accepted a container whose flags byte was edited — the header "
        "is not in the AAD on the Nim side, so the two implementations disagree"
    )
    assert "tampered payload" in proc.stderr, proc.stderr
    assert payload is None


@pytest.mark.invariant("INV-CRYPTO-04")
@pytest.mark.parametrize("field,offset", [("version", 8), ("flags", 10), ("iters", 12),
                                          ("nonce", 32), ("esecret_len", 60)])
def test_every_header_field_is_inside_the_aad(container, field, offset):
    """Byte-level coverage map of the header. If a field falls out of the AAD, only its
    parametrization goes red, so the failure names the field that regressed."""
    mutated = bytearray(container)
    mutated[offset] ^= 0x01
    assert _aad_or_rejected(bytes(mutated)) != crypto.container_aad(container), (
        f"{field} at offset {offset} is not covered by the AAD"
    )


@pytest.mark.invariant("INV-CRYPTO-04")
def test_the_tag_field_is_the_only_header_bytes_outside_the_aad(container):
    """A GCM tag cannot authenticate itself; everything else before the ciphertext must be
    in. Stated as an equality so a future 'small' header addition cannot silently escape."""
    eslen = struct.unpack_from("<H", container, 60)[0]
    header = container[:62 + eslen]
    aad = crypto.container_aad(container)
    assert aad == header[:44] + header[60:]
    assert len(aad) == len(header) - 16
    for off in range(len(header)):
        if 44 <= off < 60:
            continue
        mutated = bytearray(container)
        mutated[off] ^= 0x01
        assert _aad_or_rejected(bytes(mutated)) != aad, (
            f"header byte {off} is outside the AAD"
        )


@pytest.mark.invariant("INV-CRYPTO-04")
def test_version_is_bumped_and_both_implementations_agree(container):
    """The format changed, so the version field must say so — otherwise a v1 container and
    a v2 container are indistinguishable and the failure reads as 'wrong secret'."""
    assert crypto.CONTAINER_VERSION == 2
    assert struct.unpack_from("<H", container, 8)[0] == 2
    consts = _nim_consts()
    assert consts["ContainerVersion"] == crypto.CONTAINER_VERSION
    assert consts["TagOff"] == crypto.TAG_OFF
    assert consts["HdrFixed"] == crypto.HDR_FIXED


@pytest.mark.invariant("INV-CRYPTO-02")
def test_nim_builds_the_same_aad_bytes(container):
    """Source-level parity for the AAD construction, in the style test_container.py uses
    for the offsets. Weaker than the interop test above; kept because it names the drift."""
    body = " ".join(_nim_proc("parseBox").split())
    assert "result.aad = b[0 ..< TagOff]" in body, body
    assert "result.aad.add b[TagOff+16 ..< HdrFixed+eslen]" in body, body


@pytest.mark.invariant("INV-CRYPTO-04")
def test_nim_refuses_a_version_1_container_before_asking_for_a_secret(harness, container,
                                                                     tmp_path):
    """A v1 container in front of a v2 launcher must say so, not fail as 'wrong secret'.
    Run with NO secret available: the version check has to fire first, or the user gets a
    prompt for a secret that could never have worked."""
    downgraded = bytearray(container)
    struct.pack_into("<H", downgraded, 8, 1)
    proc, _ = _run(harness, bytes(downgraded), tmp_path, secret=None)
    assert proc.returncode != 0
    assert "version" in proc.stderr, proc.stderr
    assert "License secret" not in proc.stderr, (
        "the launcher prompted for a secret before noticing the container is unreadable"
    )


# --------------------------------------------------------------------------------------
# INV-CRYPTO-06 — post-decryption plaintext bounds
# --------------------------------------------------------------------------------------

@pytest.mark.invariant("INV-CRYPTO-06")
def test_forged_plaintext_round_trips(harness, tmp_path):
    """Control for the two tests below: _forge produces containers the real reader accepts,
    so a rejection there is the bounds check and not a broken fixture."""
    policy = b'{"expires":"","geo":[],"machine":"","user":""}'
    blob = _forge(struct.pack("<I", len(policy)) + policy + PAYLOAD)
    proc, payload = _run(harness, blob, tmp_path)
    assert proc.returncode == 0, proc.stderr
    assert payload == PAYLOAD


@pytest.mark.invariant("INV-CRYPTO-06")
@pytest.mark.parametrize("plen", [0xFFFFFFFF, 0x7FFFFFFF, 4096])
def test_oversized_policy_length_is_refused_not_crashed(harness, tmp_path, plen):
    """An authenticated-but-nonsense policy length must produce a diagnostic exit.

    Reachable only by a secret-holder, so it is robustness rather than a bypass — but an
    out-of-range slice or a negative-length allocation in the launcher is a crash with no
    explanation, and on 32-bit it is a negative length passed to newString."""
    blob = _forge(struct.pack("<I", plen) + b'{"geo":[]}' + PAYLOAD)
    proc, payload = _run(harness, blob, tmp_path)
    assert proc.returncode == 5, f"rc={proc.returncode} err={proc.stderr}"
    assert "policy length" in proc.stderr, proc.stderr
    assert "Error: unhandled exception" not in proc.stderr and "Traceback" not in proc.stderr, (
        f"unhandled Nim defect instead of a bounds check: {proc.stderr}"
    )
    assert payload is None


@pytest.mark.invariant("INV-CRYPTO-06")
def test_plaintext_shorter_than_its_length_prefix_is_refused(harness, tmp_path):
    blob = _forge(b"\x01\x02")          # two bytes: not even a length prefix
    proc, _ = _run(harness, blob, tmp_path)
    assert proc.returncode == 5, f"rc={proc.returncode} err={proc.stderr}"
    assert "length prefix" in proc.stderr, proc.stderr


@pytest.mark.invariant("INV-CRYPTO-06")
def test_truncated_container_header_is_refused(harness, container, tmp_path):
    proc, _ = _run(harness, container[:40], tmp_path)
    assert proc.returncode == 5, f"rc={proc.returncode} err={proc.stderr}"
    assert "truncated" in proc.stderr, proc.stderr


# --------------------------------------------------------------------------------------
# INV-CRYPTO-05 — constant-time tag comparison (source-level; see the module docstring)
# --------------------------------------------------------------------------------------

@pytest.mark.invariant("INV-CRYPTO-05")
def test_tag_comparison_has_no_early_exit():
    """The old loop was `if tag[i] != box.tag[i]: quit(...)` — it returns after the first
    differing byte, which leaks the length of the matching prefix by timing.

    This reads the source, and that is a real limitation: it proves the shape of the
    comparison, not its timing. A timing assertion inside pytest would measure the
    scheduler.
    """
    body = _nim_proc("openContainer")
    loop = re.search(r"for i in 0 \.\.< 16:.*", body)
    assert loop, "no 16-byte tag comparison loop found in openContainer"
    assert "quit" not in loop.group(0), (
        "the tag comparison exits the loop early — restore the accumulate-then-compare form"
    )
    assert re.search(r"diff\s*=\s*diff\s+or\s*\(\s*tag\[i\]\s+xor\s+box\.tag\[i\]\s*\)",
                     loop.group(0)), loop.group(0)
    assert re.search(r"if\s+diff\s*!=\s*0'u8:\s*\n\s*quit", body), (
        "the accumulated difference is never acted on — a container with any tag would open"
    )


@pytest.mark.invariant("INV-CRYPTO-05")
def test_a_wrong_tag_is_still_rejected(harness, container, tmp_path):
    """Constant-time is worthless if it stopped rejecting. Flip each end of the tag."""
    for offset in (44, 59):
        mutated = bytearray(container)
        mutated[offset] ^= 0x80
        proc, payload = _run(harness, bytes(mutated), tmp_path)
        assert proc.returncode != 0 and payload is None, (
            f"a container with a corrupted tag byte at {offset} was accepted"
        )
        assert "tampered payload" in proc.stderr, proc.stderr


# --------------------------------------------------------------------------------------
# INV-SECRET-01 — the typed secret is never echoed
# --------------------------------------------------------------------------------------

def _prompt_over_pty(harness_exe: Path, blob: bytes, tmp_path: Path, typed: bytes,
                     timeout: float = 30.0) -> tuple[bytes, int]:
    """Run the decryptor on a real pty with ECHO left ON, type `typed`, return (output, rc).

    ECHO on is the point: that is what a terminal does, and it is why `stdin.readLine()`
    leaks. A no-echo read turns ECHO off for the duration, so the typed bytes never come
    back down the master. Nothing here simulates the terminal — it is a kernel pty.
    """
    box, out = tmp_path / "box.bin", tmp_path / "out.bin"
    out.unlink(missing_ok=True)
    box.write_bytes(blob)
    env = dict(os.environ)
    env.pop("HARUPACK_SECRET", None)
    master, slave = pty.openpty()
    proc = subprocess.Popen([str(harness_exe), str(box), str(out)],
                            stdin=slave, stdout=slave, stderr=slave, env=env, close_fds=True)
    os.close(slave)
    captured = bytearray()
    sent = False
    deadline = time.time() + timeout
    try:
        while time.time() < deadline:
            r, _, _ = select.select([master], [], [], 0.2)
            if r:
                try:
                    chunk = os.read(master, 4096)
                except OSError:
                    break
                if not chunk:
                    break
                captured += chunk
            if not sent and b"License secret" in captured:
                time.sleep(0.3)        # let the reader finish turning ECHO off
                os.write(master, typed + b"\n")
                sent = True
            if sent and proc.poll() is not None:
                # drain whatever is still buffered in the pty
                while select.select([master], [], [], 0.2)[0]:
                    try:
                        chunk = os.read(master, 4096)
                    except OSError:
                        break
                    if not chunk:
                        break
                    captured += chunk
                break
        assert sent, f"never saw the secret prompt; got {bytes(captured)!r}"
        proc.wait(timeout=10)
    finally:
        if proc.poll() is None:
            proc.kill()
            proc.wait(timeout=10)
        os.close(master)
    return bytes(captured), proc.returncode


@pytest.mark.skipif(sys.platform == "win32", reason="pty is POSIX-only")
@pytest.mark.invariant("INV-SECRET-01")
def test_typed_secret_is_not_echoed_to_the_terminal(harness, container, tmp_path):
    """The load-bearing test for INV-SECRET-01, over a kernel pty with echo enabled.

    It also asserts the open SUCCEEDS: a no-echo read that mangles the secret would pass a
    'the secret is not on screen' assertion for entirely the wrong reason.
    """
    captured, rc = _prompt_over_pty(harness, container, tmp_path, SECRET)
    assert rc == 0, f"the secret typed at the prompt did not open the container: {captured!r}"
    assert (tmp_path / "out.bin").read_bytes() == PAYLOAD
    assert SECRET not in captured, (
        f"the license secret was echoed to the terminal: {captured!r} — it is now in the "
        f"scrollback, in `script` output, and in any CI log that captured this session"
    )
    assert b"License secret" in captured, "the prompt itself must still be shown"


@pytest.mark.skipif(sys.platform == "win32", reason="pty is POSIX-only")
@pytest.mark.invariant("INV-SECRET-01")
def test_the_echo_check_can_see_an_echo(harness, container, tmp_path):
    """Guard-of-guards. If the pty were misconfigured (ECHO off at the master, or the
    input never reaching the child), the test above would pass no matter what the reader
    does. So: type a wrong secret at the same prompt through the same path and require
    that the harness saw it — proof the bytes really are delivered and the open really is
    driven by what was typed."""
    captured, rc = _prompt_over_pty(harness, container, tmp_path, b"definitely-wrong-secret")
    assert rc == 5, f"a wrong typed secret must fail the open; rc={rc} out={captured!r}"
    assert b"tampered payload" in captured or b"wrong secret" in captured, captured
    assert b"definitely-wrong-secret" not in captured, (
        "even a wrong secret must not be echoed — users mistype their real one"
    )


@pytest.mark.invariant("INV-SECRET-01")
def test_the_secret_prompt_uses_a_no_echo_read():
    """Pins the mechanism, so a refactor back to a line read is caught even on a box with
    no pty available."""
    body = _nim_proc("resolveSecret")
    assert "readPasswordFromStdin" in body, body
    assert "stdin.readLine" not in body, (
        "resolveSecret is reading the secret with an echoing line read again"
    )
