"""`--author` — emit a corpus script covering what previous runs did NOT.

Adopted from lotek's `tests/busybody/author.py` (T-015). Its version generates a corpus
script covering what prior runs missed; this is the same idea aimed at this catalogue.

## The question it answers

"575/575 passed" is the number everyone quotes and it is not the interesting one. `--analyze`
already attacks that from one side — the fingerprint census asks whether a sweep bought
anything, or confirmed the same fact twenty-five times. This attacks it from the other side:
**what has never been run at all?**

Those are different holes and they fail differently. A sweep that runs everything and learns
nothing is expensive; a sweep that quietly never touched a whole persona is a clean bill of
health for code nobody looked at, which is worse.

## What counts as a gap

Three, in descending order of how much the silence costs:

  * **A case that has never run.** Nothing at all is known about it. If it was added and
    never selected, its `expect` is an untested opinion.
  * **A trait that has never fired.** Selection and firing are separate, and a trait with a
    low per-action perturbation probability can be selected repeatedly and act never. The
    catalogue says it perturbs something; no run has confirmed it perturbs anything.
  * **A pair of LAYERS that have never been stacked.** The whole premise of composition is
    that the interesting failures are between mechanisms rather than between variations of
    one mechanism, so an unexercised layer pair is a claim the harness makes and has not
    tested. Pairs rather than triples on purpose: the triple space is large enough that
    "never seen" stops being informative.

## What it deliberately does NOT do

It does not run anything. It writes a shell script to stdout, and the person reading it
decides. A tool that notices a gap and then closes it unattended is a tool that spends four
hours of somebody's machine on a conclusion they did not ask for — and `--compose` at k=3
over this catalogue is exactly that size.

It also does not invent cases. Generating a plausible-looking case that nobody reasoned
about is how a catalogue acquires cases whose `expect` is a guess, and this repo's whole
scheme is built on `expect` being an argument somebody made.
"""
from __future__ import annotations

import itertools

import busybody_config as cfg
from busybody_compose import TRAITS
from busybody_ledger import read_jsonl, scan_runs

__all__ = ["coverage", "script_for", "print_author"]


def _journal_records(paths) -> list:
    out = []
    for run in scan_runs(paths.runs):
        out += read_jsonl(run["dir"] / "journal.jsonl")
    return out


def coverage(paths) -> dict:
    """What every recorded run has and has not exercised.

    Read from the journals rather than the ledger, and the difference matters: the ledger
    holds FINDINGS, so a case that has run a hundred times and always passed is absent from
    it. Asking the ledger "what has run?" would report every healthy case as never-run,
    which is the exact inversion of the question.
    """
    recs = _journal_records(paths)
    cases = [r for r in recs if r.get("kind") == "case"]

    ran_cases = {r.get("name") for r in cases if r.get("name")}
    known_cases = {c["name"] for c in cfg.CASES}

    fired_traits: set = set()
    seen_layer_pairs: set = set()
    for r in cases:
        fired = [n for n in (r.get("fired") or []) if n in TRAITS]
        fired_traits.update(fired)
        layers = sorted({TRAITS[n]["layer"] for n in fired})
        seen_layer_pairs.update(itertools.combinations(layers, 2))

    all_pairs = set(itertools.combinations(sorted({t["layer"] for t in TRAITS.values()}), 2))

    return {
        "runs": len(scan_runs(paths.runs)),
        "results": len(cases),
        "never_run_cases": sorted(known_cases - ran_cases),
        "never_fired_traits": sorted(set(TRAITS) - fired_traits),
        "never_paired_layers": sorted(all_pairs - seen_layer_pairs),
        "case_total": len(known_cases),
        "trait_total": len(TRAITS),
        "pair_total": len(all_pairs),
    }


def _case_lines(names: list) -> list:
    """One invocation per 12 cases. Batched because 80 separate sweeps each rebuild a
    fixture, and the fixture is the expensive part of a run by two orders of magnitude."""
    lines = []
    for i in range(0, len(names), 12):
        batch = ",".join(names[i:i + 12])
        lines.append(f"python tools/busybody.py --case {batch}")
    return lines


def script_for(cov: dict) -> list:
    """The shell script, as lines. Deterministic: sorted inputs, no clock."""
    L = ["#!/usr/bin/env bash",
         "# Generated by `python tools/busybody.py --author`.",
         "#",
         "# Every line below covers something NO recorded run has exercised. Read it before",
         "# running it: this is a proposal, not a plan, and the composed lines are the",
         "# expensive ones. Nothing here is a claim that a gap is a bug — it is a claim",
         "# that the silence is unearned.",
         "set -euo pipefail",
         ""]
    if cov["never_run_cases"]:
        L += [f"# {len(cov['never_run_cases'])} of {cov['case_total']} case(s) have never "
              f"run. Nothing at all is known about these:",
              "#   their `expect` set is an untested opinion until one of them runs once."]
        L += _case_lines(cov["never_run_cases"])
        L.append("")
    if cov["never_fired_traits"]:
        L += [f"# {len(cov['never_fired_traits'])} of {cov['trait_total']} trait(s) have "
              f"never FIRED. Selection and firing are separate:",
              "#   a trait with a low perturbation probability can be selected often and act",
              "#   never. --compose-only forces every named trait to fire, which is the only",
              "#   way to establish that it perturbs anything at all."]
        for name in cov["never_fired_traits"]:
            L.append(f"python tools/busybody.py --compose-only {name} --compose-runs 1")
        L.append("")
    if cov["never_paired_layers"]:
        L += [f"# {len(cov['never_paired_layers'])} of {cov['pair_total']} LAYER pair(s) have "
              f"never been stacked together.",
              "#   Composition's whole premise is that the interesting failures live between",
              "#   mechanisms rather than between variations of one, so an unexercised pair",
              "#   is a claim this harness makes and has not tested.",
              "#   These are sampled, not enumerated: the pair is the target, and one stack",
              "#   that happens to hit it is worth more than every stack that could."]
        for a, b in cov["never_paired_layers"]:
            pair = _first_pair(a, b)
            if pair:
                L.append(f"python tools/busybody.py --compose-only {pair[0]},{pair[1]} "
                         f"--compose-runs 1   # layers {a} + {b}")
        L.append("")
    if not (cov["never_run_cases"] or cov["never_fired_traits"]
            or cov["never_paired_layers"]):
        L += ["# Nothing to propose: every case has run, every trait has fired, and every",
              "# layer pair has been stacked at least once. That is coverage, not assurance —",
              "# `--analyze` is the tool that asks whether any of it bought anything.",
              ""]
    return L


def _first_pair(layer_a: str, layer_b: str) -> tuple:
    """One conflict-free trait from each layer, deterministically chosen.

    Sorted-first rather than random: `--author` run twice on the same history must emit the
    same script, or its output cannot be diffed and cannot be reviewed.
    """
    from busybody_compose import conflicts_in

    for a in sorted(n for n, t in TRAITS.items() if t["layer"] == layer_a):
        for b in sorted(n for n, t in TRAITS.items() if t["layer"] == layer_b):
            if not conflicts_in((a, b)):
                return (a, b)
    return ()


def print_author(paths) -> int:
    """Write the corpus script to stdout. Always exit 0 — a gap is not a failure."""
    cov = coverage(paths)
    if not cov["runs"]:
        print("# no recorded runs, so every case, trait and layer pair is a gap.",
              "# Run `python tools/busybody.py` once before asking what it missed.",
              sep="\n")
        return 0
    print("\n".join(script_for(cov)))
    print(f"# Based on {cov['results']} recorded result(s) across {cov['runs']} run(s).")
    print("# A gap is not a defect. It is a place where a clean bill of health was issued")
    print("# for something nobody looked at, which is the cheaper of the two problems to fix.")
    return 0
