"""The git-tracked results ledger, and the page rendered from it.

Both halves are deliberately offline and deterministic: `emit()` renders
`top_n_pypi_stats.md` from `packages.toml` (the row set) plus the ledger (the results), with
no network and no clock beyond the dates already recorded — so the committed page reproduces
exactly from the committed ledger.

Split out of exam.py 2026-09-13 (INV-MODULARITY-01). Unchanged otherwise.
"""
from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

PACKAGES = REPO / "flex" / "packages.toml"
LEDGER = REPO / "flex" / "exam-results.json"
PAGE = REPO / "top_n_pypi_stats.md"
MARKER = "EXAM_OK"

from exam_fetch import top_n  # noqa: E402


# ─────────────────────────────────────────────────────────── the ledger (git-tracked)
def load_ledger() -> dict:
    if LEDGER.exists():
        return json.loads(LEDGER.read_text(encoding="utf-8"))
    return {}


def save_ledger(led: dict) -> None:
    # Sorted keys + trailing newline so the committed file diffs cleanly and deterministically.
    LEDGER.write_text(json.dumps(led, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def today() -> str:
    return _dt.date.today().isoformat()


def apply_result(led: dict, rank: int, res: dict) -> None:
    e = led.get(res["name"], {})
    e["rank"] = rank
    e["name"] = res["name"]
    for k in ("version", "repo_url", "pypi_url", "layout", "mb"):
        if res.get(k):
            e[k] = res[k]
    e["tests"] = res.get("tests", e.get("tests", 0))
    e["passed"] = bool(res["passed"])
    e["last_run"] = today()
    e["error"] = res.get("error", "")
    if res["passed"]:
        e["last_passed"] = today()             # only a pass moves this date
    led[res["name"]] = e


# ─────────────────────────────────────────────────────────── emit (offline, deterministic)
def emit() -> None:
    """Render top_n_pypi_stats.md from packages.toml (the row set) + the ledger (the results).
    No network, no clock beyond the dates already recorded in the ledger — so the committed
    page reproduces exactly from the committed ledger."""
    pkgs = top_n()
    led = load_ledger()
    n = len(pkgs)
    passing = sum(1 for p in pkgs if led.get(p["name"], {}).get("passed"))
    examined = sum(1 for p in pkgs if led.get(p["name"], {}).get("last_run"))
    asof = max((led.get(p["name"], {}).get("last_run", "") for p in pkgs), default="")

    lines = [
        "# top-N PyPI packages — the flex exam",
        "",
        "<!-- GENERATED by tools/exam.py — do not hand-edit. Regenerate: "
        "`python tools/exam.py emit`. -->",
        "",
        "Each package below **sits its own test suite** from inside a haru-pack **thick** "
        "binary, with the network denied. A pass is the strongest statement this project "
        "makes about a packaged dependency: not that it imports, but that its own tests pass "
        "against the code the payload actually carried. Mechanism and rationale: "
        "[`docs/FLEX.md`](docs/FLEX.md) · invariant `INV-TIER-01`.",
        "",
        f"**{passing} of {n} passing**, {examined} examined"
        + (f", as of {asof}." if asof else "."),
        "",
        "| # | Package | Repo | Exam | Tests | Last passed |",
        "|--:|---------|------|:----:|------:|-------------|",
    ]
    for p in pkgs:
        name = p["name"]
        e = led.get(name, {})
        pypi = e.get("pypi_url") or f"https://pypi.org/project/{name}/"
        repo = e.get("repo_url") or ""
        repo_cell = f"[source]({repo})" if repo else "—"
        if not e.get("last_run"):
            exam = "·"                          # not yet examined
        elif e.get("passed"):
            exam = "✅"
        else:
            exam = "❌"
        tests = str(e.get("tests", "")) if e.get("passed") else ""
        last = e.get("last_passed", "") or "—"
        lines.append(f"| {p.get('rank', '')} | [{name}]({pypi}) | {repo_cell} | "
                     f"{exam} | {tests} | {last} |")
    lines += [
        "",
        "Legend: ✅ passed its own suite offline · ❌ examined, did not pass · "
        "· not yet examined.",
        "",
        "A ❌ is not always a packaging defect — a suite may need a system library, a display, "
        "or the network, none of which a thick binary provides. The `error` field in "
        "[`flex/exam-results.json`](flex/exam-results.json) records why. `hard_targets` "
        "(torch, playwright, …) are a separate, harder axis and are not counted here.",
        "",
    ]
    PAGE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {PAGE.relative_to(REPO)}  ({passing}/{n} passing, {examined} examined)")

