#!/usr/bin/env python3
"""Refresh the PyPI download ranking used by the flex harness.

    python tools/fetch-top-pypi.py            # fetch, write snapshot + flex/sources.toml
    python tools/fetch-top-pypi.py --check    # verify the committed extract matches a fresh fetch

WHY FETCHING AND GENERATING ARE SEPARATE STEPS

`flex/packages.toml` has to be reproducible: same inputs, byte-identical output, offline,
years from now. A generator that reaches out to the network cannot promise that — the
ranking changes every month, so the "same" command produces a different file each time.

So the network step is here, and it is a deliberate act with a reviewable diff:

    fetch  ->  flex/snapshots/<date>.json   (raw, big, GITIGNORED)
           ->  flex/sources.toml            (small extract + provenance, COMMITTED)

    generate (tools/gen-package-manifest.py, no network)
           ->  flex/packages.toml           (COMMITTED)

The committed extract — not the raw snapshot — is the generator's input. That is what keeps
regeneration reproducible with the big file gitignored. The snapshot's sha256 is recorded
so anyone who refetches can tell whether they got the same upstream bytes we did.

Refreshing is expected to change the list. That is a decision someone makes and reviews,
not something that drifts underneath the test suite.

NO AI REQUIRED. One HTTP GET and some TOML writing; read it and run the pieces by hand.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FLEX = REPO / "flex"
SNAPSHOTS = FLEX / "snapshots"
SOURCES = FLEX / "sources.toml"

URL = "https://hugovk.github.io/top-pypi-packages/top-pypi-packages.min.json"
HOMEPAGE = "https://hugovk.github.io/top-pypi-packages/"
# How many names to keep in the committed extract. Keeping headroom means growing the flex
# matrix (top-25 -> top-250 and beyond) does not require a refetch, and so does not silently
# pull in a different month's ranking at the same time. Override with --keep; the default is a
# fresh top-1000, enough for a top-250 exam with curation slack.
KEEP = 1000


def fetch() -> tuple:
    req = urllib.request.Request(URL, headers={"User-Agent": "haru-pack-flex"})
    raw = urllib.request.urlopen(req, timeout=120).read()
    return raw, json.loads(raw)


def extract(doc: dict, keep: int = KEEP) -> list:
    rows = doc.get("rows") or []
    if not rows:
        raise SystemExit("upstream returned no rows; refusing to write an empty extract")
    return [r["project"] for r in rows[:keep]]


def render(names: list, digest: str, last_update: str, source: str) -> str:
    lines = [
        "# flex harness — the PyPI download ranking, extracted.",
        "#",
        "# GENERATED by tools/fetch-top-pypi.py. Safe to read; edit only if you know why.",
        "#",
        "# This is the committed INPUT to tools/gen-package-manifest.py. The raw upstream",
        "# snapshot it came from is gitignored (it is ~1 MB of names we do not use), so this",
        "# file is what makes flex/packages.toml reproducible offline.",
        "#",
        "# `ranking` is in download order: index 0 is the most-downloaded package. Download",
        "# COUNTS are deliberately not stored — they change every day and would make this file",
        "# churn without changing which packages we test.",
        "",
        "# Download order: index 0 is the most-downloaded package.",
        "ranking = [",
    ]
    for i in range(0, len(names), 6):
        lines.append("  " + ", ".join(f'"{n}"' for n in names[i:i + 6]) + ",")
    lines += [
        "]",
        "",
        "[source]",
        'name = "Top PyPI Packages"',
        f'url = "{URL}"',
        f'homepage = "{HOMEPAGE}"',
        f'upstream_source = "{source}"',
        f'last_update = "{last_update}"',
        f'snapshot_sha256 = "{digest}"',
        f"kept = {len(names)}",
        'note = """',
        "Derived from PyPI's public download statistics. Counts include mirrors and CI, so",
        'this ranks what gets DOWNLOADED, not what is most used by humans — good enough for',
        'picking a representative breadth sample, which is all it is for."""',
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare the committed extract against a fresh fetch; write nothing")
    ap.add_argument("--keep", type=int, default=KEEP,
                    help=f"how many top ranked names to keep in the extract (default {KEEP})")
    a = ap.parse_args()

    raw, doc = fetch()
    digest = hashlib.sha256(raw).hexdigest()
    names = extract(doc, a.keep)
    last_update = str(doc.get("last_update", "")).strip()
    source = str(doc.get("source", "")).strip()

    if a.check:
        if not SOURCES.exists():
            print(f"{SOURCES} does not exist", file=sys.stderr)
            return 1
        current = SOURCES.read_text()
        fresh = render(names, digest, last_update, source)
        if current == fresh:
            print(f"up to date (snapshot {digest[:16]}…, upstream last_update {last_update})")
            return 0
        print("the committed extract differs from upstream.")
        print(f"  committed snapshot_sha256: "
              f"{[l for l in current.splitlines() if 'snapshot_sha256' in l]}")
        print(f"  fresh snapshot_sha256:     {digest}")
        print("\nRun without --check to refresh, then review the diff:")
        print("  git diff flex/sources.toml")
        return 1

    SNAPSHOTS.mkdir(parents=True, exist_ok=True)
    stamp = (last_update.split()[0] or "unknown").replace(":", "-")
    snap = SNAPSHOTS / f"top-pypi-{stamp}.json"
    snap.write_bytes(raw)
    (snap.with_suffix(".json.sha256")).write_text(f"{digest}  {snap.name}\n")

    SOURCES.write_text(render(names, digest, last_update, source))
    print(f"snapshot : {snap.relative_to(REPO)}  ({len(raw)} bytes, gitignored)")
    print(f"extract  : {SOURCES.relative_to(REPO)}  ({len(names)} names)")
    print(f"sha256   : {digest}")
    print("\nNext: python tools/gen-package-manifest.py")
    print("Then review:  git diff flex/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
