#!/usr/bin/env python3
"""Generate flex/packages.toml from flex/sources.toml + flex/curation.toml.

    python tools/gen-package-manifest.py           # write flex/packages.toml
    python tools/gen-package-manifest.py --check   # fail if the committed file is stale
    python tools/gen-package-manifest.py -n 250    # grow the top-N list

DETERMINISTIC BY CONSTRUCTION

No network. No clock. No randomness. Same two input files in, byte-identical output.
That is the whole point: `flex/packages.toml` records which packages the flex harness
tests, and anyone must be able to reproduce it — offline, years from now, without asking
anybody what the ranking looked like that day.

The ranking's provenance (source URL, upstream timestamp, snapshot sha256) lives in
flex/sources.toml and is copied into the header of the generated file, so a reader of
packages.toml alone can still tell where the list came from. Refreshing the ranking is
`tools/fetch-top-pypi.py`, which is a separate, deliberate act.

NO AI REQUIRED. Reads two TOML files, writes a third.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from haru_pack import scaffold, tomlio  # noqa: E402

FLEX = REPO / "flex"
SOURCES = FLEX / "sources.toml"
CURATION = FLEX / "curation.toml"
OUT = FLEX / "packages.toml"

DEFAULT_TOP_N = 25


def _q(s: str) -> str:
    """A TOML basic string. Snippets are multi-line, so they get triple quotes."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ml(s: str) -> str:
    body = s.strip("\n")
    return '"""\n' + body + '\n"""'


def build(sources: dict, curation: dict, top_n: int) -> str:
    src = sources.get("source", {})
    ranking = sources.get("ranking") or []
    if not ranking:
        raise SystemExit("flex/sources.toml has an empty `ranking`")

    pkgs = curation.get("package", {})
    hards = curation.get("hard", {})
    defaults = curation.get("defaults", {})
    default_tier = defaults.get("tier", "default")
    default_python = defaults.get("python", "3.12")

    # Walk the ranking in order, skipping curated-out entries, until we have top_n.
    chosen, skipped = [], []
    for name in ranking:
        if len(chosen) >= top_n:
            break
        entry = pkgs.get(name, {})
        if entry.get("skip"):
            skipped.append((name, entry.get("skip_reason", "").strip()))
            continue
        chosen.append(name)
    if len(chosen) < top_n:
        raise SystemExit(
            f"only {len(chosen)} of {top_n} packages available from a ranking of "
            f"{len(ranking)}; refresh with tools/fetch-top-pypi.py or lower -n")

    L = [
        "# flex harness — the package matrix.",
        "#",
        "# GENERATED by tools/gen-package-manifest.py from flex/sources.toml and",
        "# flex/curation.toml. Do not hand-edit: your changes are lost on regeneration.",
        "# To change WHICH packages: edit flex/curation.toml. To change the RANKING:",
        "# run tools/fetch-top-pypi.py and review the diff.",
        "#",
        "# Regenerate:  python tools/gen-package-manifest.py",
        "# Verify:      python tools/gen-package-manifest.py --check",
        "",
        "schema_version = 1",
        f"top_n = {top_n}",
        "",
        "[source]",
        f"name = {_q(src.get('name', ''))}",
        f"url = {_q(src.get('url', ''))}",
        f"upstream_source = {_q(src.get('upstream_source', ''))}",
        f"last_update = {_q(src.get('last_update', ''))}",
        f"snapshot_sha256 = {_q(src.get('snapshot_sha256', ''))}",
        "",
    ]

    if skipped:
        L.append("# Deliberately excluded from the ranking walk (see flex/curation.toml):")
        for name, reason in skipped:
            first = " ".join(reason.split())[:96]
            L.append(f"#   {name}: {first}")
        L.append("")

    L += ["# ---------- top25: breadth ----------", ""]
    for rank, name in enumerate(chosen, 1):
        e = pkgs.get(name, {})
        L += ["[[package]]",
              f"name = {_q(name)}",
              "list = \"top25\"",
              f"rank = {rank}",
              f"import_name = {_q(e.get('import_name', name.replace('-', '_')))}",
              f"tier = {_q(e.get('tier', default_tier))}",
              f"python = {_q(e.get('python', default_python))}"]
        if e.get("smoke"):
            L.append(f"smoke = {_ml(e['smoke'])}")
        if e.get("why"):
            L.append(f"why = {_q(' '.join(e['why'].split()))}")
        L.append("")

    L += ["# ---------- hard_targets: where a packaging tool earns its keep ----------", ""]
    for name in sorted(hards):
        h = hards[name]
        L += ["[[package]]",
              f"name = {_q(name)}",
              'list = "hard_targets"',
              f"known = {_q(h.get('known', name))}",
              f"import_name = {_q(h.get('import_name', name.replace('-', '_')))}",
              f"tier = {_q(h.get('tier', 'thick'))}",
              f"python = {_q(h.get('python', default_python))}",
              f"corner = {_q(' '.join(h.get('corner', '').split()))}"]
        if h.get("expect"):
            L.append(f"expect = {_q(' '.join(h['expect'].split()))}")
        if h.get("expect_failure"):
            L.append("expect_failure = true")
        # Steps come from scaffold.KNOWN rather than being restated here: that table is the
        # text haru-pack tells users to declare, so the harness must test the same text.
        #
        # They are ALTERNATIVES, not both. KNOWN offers playwright a `bundle` step (runs at
        # build time, output ships) and a `post_install` step (runs on the target, first
        # run) as two ways to solve the same problem. Emitting both would ship a thick
        # binary carrying a post_install step that thick's own UV_OFFLINE=1 forbids
        # (INV-TIER-02). Pick by tier: bundle for thick, post_install otherwise.
        k = scaffold.KNOWN.get(h.get("known", name), {})
        tier = h.get("tier", "thick")
        block = "bundle" if tier == "thick" else "post_install"
        if k.get(block):
            L.append(f"{block} = {_ml(k[block])}")
        elif tier == "thick" and k.get("post_install"):
            # No bundle alternative exists; say so rather than silently shipping nothing.
            L.append('steps_note = "scaffold.KNOWN offers only a post_install step for this '
                     'package, which thick forbids (INV-TIER-02); nothing was declared"')
        if h.get("smoke"):
            L.append(f"smoke = {_ml(h['smoke'])}")
        L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    ap.add_argument("-n", "--top-n", type=int, default=DEFAULT_TOP_N)
    a = ap.parse_args()

    for f in (SOURCES, CURATION):
        if not f.exists():
            print(f"missing {f.relative_to(REPO)}", file=sys.stderr)
            return 1

    text = build(tomlio.load(SOURCES), tomlio.load(CURATION), a.top_n)

    if a.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(REPO)} does not exist; run without --check", file=sys.stderr)
            return 1
        if OUT.read_text() == text:
            print(f"{OUT.relative_to(REPO)} is up to date")
            return 0
        print(f"{OUT.relative_to(REPO)} is STALE — regenerate it:", file=sys.stderr)
        print("    python tools/gen-package-manifest.py", file=sys.stderr)
        return 1

    OUT.write_text(text)
    n_hard = len(tomlio.load(CURATION).get("hard", {}))
    print(f"wrote {OUT.relative_to(REPO)}  ({a.top_n} top-N + {n_hard} hard targets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
