"""`--emit-c` — ship the Nim C backend's OWN output, so the kit needs no Nim toolchain.

Plain `.c`/`.h` files already generated for your `--target`, plus `nimbase.h` and the
vendored xz headers. Only a `zig` (on PATH, or via `HARU_ZIG`) is needed to rebuild.

Split out of emit.py 2026-09-13 (INV-MODULARITY-01). Unchanged otherwise.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from .. import toolchain
from ..paths import launcher_src_dir
from .compilecmd import compile_script_body
from .errors import EmitError
from .kit import _find_nimbase


def emit_c_sources(nimcache: Path, dest: Path, triple: str, exe: str, log=None) -> str:
    """Write the C source tree + shim + compile.sh (compile+link only) into `dest`.

    Returns the shim's filename (relative to `dest`) so the caller can reference it. The
    compile.sh written here stops after the link; `finish_kit` appends the assemble step
    once the payload is known."""
    say = log or (lambda _m: None)
    nimcache = Path(nimcache)
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    jpath = nimcache / "launcher.json"
    if not jpath.exists():
        raise EmitError(f"Nim build manifest missing: {jpath} (expected after a normal build)")
    nim_json = json.loads(jpath.read_text())

    # Vendor every source Nim compiled — the Nim `@m…`/`@p…`/`@n…` .c files (from the
    # nimcache) and the xz .c (from the launcher tree) both appear as compile[i][0]. Nim's
    # mangled names are unique, but two sources sharing a basename would clobber silently and
    # link the wrong object, so refuse that rather than emit a kit that builds the wrong thing.
    seen: dict[str, Path] = {}
    for src, _cmd in nim_json["compile"]:
        s = Path(src)
        prev = seen.get(s.name)
        if prev is not None and prev != s:
            raise EmitError(
                f"two sources share the basename {s.name!r} ({prev} and {s}); the vendored "
                f"kit would clobber one. This is a Nim/emit assumption break — please report it.")
        seen[s.name] = s
        shutil.copy2(s, dest / s.name)
    # Vendor headers so `-I.` resolves everything Nim reached by absolute path: the xz
    # headers next to the xz .c, and nimbase.h from Nim's lib.
    for h in (launcher_src_dir() / "xz").glob("*.h"):
        shutil.copy2(h, dest / h.name)
    shutil.copy2(_find_nimbase(nim_json), dest / "nimbase.h")

    # A durable, machine-independent shim (never this build's tempdir path): it calls
    # `${HARU_ZIG:-zig} cc -target <triple>`, so the kit works on the packager's machine given
    # zig on PATH. Reuses toolchain.zig_cc_shim — the same helper --emit-nim's kit uses — so
    # the GCC-only-flag translation matches a real build.
    toolchain.zig_cc_shim("${HARU_ZIG:-zig}", triple, dest / "zig-cc")
    shim_name = "./zig-cc"

    body = compile_script_body(nim_json, exe, shim_name)
    script = ("#!/bin/sh\n"
              "# Recompile the haru-pack launcher stub, then reassemble the binary.\n"
              "# Generated by haru-pack --emit-c. Needs no Nim; needs a zig on PATH\n"
              "# (or set HARU_ZIG to a zig binary). No absolute build-host paths.\n"
              "set -e\n"
              'cd "$(dirname "$0")"\n'
              + body)
    (dest / "compile.sh").write_text(script)
    (dest / "compile.sh").chmod(0o755)
    say(f"--emit-c: wrote C reproduction kit to {dest} "
        f"({len(nim_json['compile'])} sources; recompile with `sh compile.sh` + a zig on PATH)")
    return shim_name
